"""added default timestamp

Revision ID: de8c26a3ee97
Revises: 146db0fcf26d
Create Date: 2025-03-05 07:40:30.676030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8c26a3ee97'
down_revision = '146db0fcf26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elevator',
    sa.Column('elevator_id', sa.Integer(), nullable=False),
    sa.Column('current_floor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('resting_floor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('elevator_id')
    )
    op.create_table('demand',
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('elevator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevator.elevator_id'], ),
    sa.PrimaryKeyConstraint('demand_id')
    )
    op.create_table('elevator_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('elevator_id', sa.Integer(), nullable=False),
    sa.Column('resting_floor', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevator.elevator_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elevator_history')
    op.drop_table('demand')
    op.drop_table('elevator')
    # ### end Alembic commands ###
