services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devtest_db
      POSTGRES_USER: devsaieh
      POSTGRES_PASSWORD: saiehpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/DEVTEST
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://devsaieh:saiehpass@db:5432/devtest_db
      ENV: development

volumes:
  pgdata: