version: '3.9'
services:
  api:
    image: elevator_storage
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "uvicorn src.main:app --host 0.0.0.0 --port 8000"]
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: ./.env