# Generated by Django 4.1.8 on 2023-04-30 21:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("current_floor", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField()),
                (
                    "source_floor",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(163),
                        ]
                    ),
                ),
                (
                    "destination_floor",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(163),
                        ]
                    ),
                ),
                (
                    "rest_floor",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(163),
                        ]
                    ),
                ),
                (
                    "elevator",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="elevator.elevator"),
                ),
            ],
        ),
    ]
