# Generated by Django 4.1.8 on 2023-04-30 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="max_floors",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(163),
                ],
            ),
            preserve_default=False,
        ),
    ]
