# Generated by Django 4.1.8 on 2023-04-30 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0002_elevator_max_floors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="call",
            old_name="timestamp",
            new_name="moment",
        ),
    ]
