# Generated by Django 4.1.8 on 2023-05-03 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0003_rename_timestamp_call_moment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Call",
            new_name="Demand",
        ),
    ]
