# Generated by Django 4.1 on 2022-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('demandFloor', models.IntegerField()),
                ('endFloor', models.IntegerField()),
                ('people', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
