"""update_update_orders

Revision ID: 43f92b833715
Revises: 74795d83684c
Create Date: 2023-09-15 16:05:14.980365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f92b833715'
down_revision: Union[str, None] = '74795d83684c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'catalog_elevator_states', ['id'])
    op.create_unique_constraint(None, 'catalog_order_categories', ['id'])
    op.create_unique_constraint(None, 'catalog_order_movements', ['id'])
    op.create_unique_constraint(None, 'catalog_order_status', ['id'])
    op.create_unique_constraint(None, 'catalog_order_types', ['id'])
    op.create_unique_constraint(None, 'elevator_orders', ['elevator_order_id'])
    op.drop_constraint('elevator_orders_elevator_order_request_status_fkey', 'elevator_orders', type_='foreignkey')
    op.drop_column('elevator_orders', 'elevator_order_request_status')
    op.create_unique_constraint(None, 'elevator_status', ['elevator_status_id'])
    op.add_column('elevators', sa.Column('elevators_request_status', sa.Integer(), nullable=True))
    op.add_column('elevators', sa.Column('elevators_request_queue', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'elevators', ['elevator_id'])
    op.create_foreign_key(None, 'elevators', 'catalog_order_status', ['elevators_request_status'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'elevators', type_='foreignkey')
    op.drop_constraint(None, 'elevators', type_='unique')
    op.drop_column('elevators', 'elevators_request_queue')
    op.drop_column('elevators', 'elevators_request_status')
    op.drop_constraint(None, 'elevator_status', type_='unique')
    op.add_column('elevator_orders', sa.Column('elevator_order_request_status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('elevator_orders_elevator_order_request_status_fkey', 'elevator_orders', 'catalog_order_status', ['elevator_order_request_status'], ['code'])
    op.drop_constraint(None, 'elevator_orders', type_='unique')
    op.drop_constraint(None, 'catalog_order_types', type_='unique')
    op.drop_constraint(None, 'catalog_order_status', type_='unique')
    op.drop_constraint(None, 'catalog_order_movements', type_='unique')
    op.drop_constraint(None, 'catalog_order_categories', type_='unique')
    op.drop_constraint(None, 'catalog_elevator_states', type_='unique')
    # ### end Alembic commands ###
