"""initial_migration

Revision ID: 6689fae13761
Revises: 
Create Date: 2023-08-28 08:14:00.240698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6689fae13761'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_elevator_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('catalog_order_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('catalog_order_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('catalog_order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('catalog_order_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('elevators',
    sa.Column('elevator_id', sa.Integer(), nullable=False),
    sa.Column('elevators_name', sa.String(length=255), nullable=False),
    sa.Column('elevators_details', sa.String(), nullable=True),
    sa.Column('elevators_floors', sa.Integer(), nullable=False),
    sa.Column('elevators_rooms', sa.Integer(), nullable=False),
    sa.Column('elevators_state', sa.Integer(), nullable=False),
    sa.Column('elevators_created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('elevators_update_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['elevators_state'], ['catalog_elevator_states.code'], ),
    sa.PrimaryKeyConstraint('elevator_id'),
    sa.UniqueConstraint('elevator_id')
    )
    op.create_table('elevator_orders',
    sa.Column('elevator_orders_id', sa.Integer(), nullable=False),
    sa.Column('elevator_id', sa.Integer(), nullable=True),
    sa.Column('elevator_order_demand_category', sa.Integer(), nullable=False),
    sa.Column('elevator_order_demand_type', sa.Integer(), nullable=True),
    sa.Column('elevator_order_demand_floor', sa.Integer(), nullable=True),
    sa.Column('elevator_order_current_floor', sa.Integer(), nullable=False),
    sa.Column('elevator_order_movement_status', sa.Integer(), nullable=False),
    sa.Column('elevator_order_request_status', sa.Integer(), nullable=False),
    sa.Column('elevator_order_created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('elevator_order_update_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.elevator_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['elevator_order_demand_category'], ['catalog_order_categories.code'], ),
    sa.ForeignKeyConstraint(['elevator_order_demand_type'], ['catalog_order_types.code'], ),
    sa.ForeignKeyConstraint(['elevator_order_movement_status'], ['catalog_order_movements.code'], ),
    sa.ForeignKeyConstraint(['elevator_order_request_status'], ['catalog_order_status.code'], ),
    sa.PrimaryKeyConstraint('elevator_orders_id'),
    sa.UniqueConstraint('elevator_orders_id')
    )
    op.create_table('elevator_status',
    sa.Column('elevator_status_id', sa.Integer(), nullable=False),
    sa.Column('elevator_id', sa.Integer(), nullable=True),
    sa.Column('elevator_status_movement', sa.Integer(), nullable=False),
    sa.Column('elevator_status_current_floor', sa.Integer(), nullable=False),
    sa.Column('elevator_status_final_floor', sa.Integer(), nullable=True),
    sa.Column('elevator_status_created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.elevator_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['elevator_status_movement'], ['catalog_order_movements.code'], ),
    sa.PrimaryKeyConstraint('elevator_status_id'),
    sa.UniqueConstraint('elevator_status_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elevator_status')
    op.drop_table('elevator_orders')
    op.drop_table('elevators')
    op.drop_table('catalog_order_types')
    op.drop_table('catalog_order_status')
    op.drop_table('catalog_order_movements')
    op.drop_table('catalog_order_categories')
    op.drop_table('catalog_elevator_states')
    # ### end Alembic commands ###
