# Generated by Django 5.0.1 on 2024-02-02 10:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_max_speed', models.FloatField(default=4)),
                ('number_of_floors', models.IntegerField(default=10)),
                ('current_floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_floor', models.IntegerField()),
                ('origin_floor', models.IntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.person')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_started_at', models.DateTimeField(default=datetime.datetime(2024, 2, 2, 7, 8, 23, 109770))),
                ('movement_finished_at', models.DateTimeField(default=datetime.datetime(2024, 2, 2, 7, 8, 23, 109770))),
                ('movement_origin_floor', models.IntegerField(default=0)),
                ('movement_final_floor', models.IntegerField(default=0)),
                ('call_origin_floor', models.IntegerField(default=0)),
                ('call_target_floor', models.IntegerField(default=0)),
                ('total_traveled_floors', models.IntegerField(default=0)),
                ('total_movement_time_ms', models.DurationField(default=datetime.timedelta(0))),
                ('avg_movement_speed_floor_by_seconds', models.FloatField(default=0)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
                ('elevator_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevatorcall')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.person')),
            ],
        ),
    ]
