# Generated by Django 5.0.1 on 2024-02-14 15:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='movement_finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 12, 3, 51, 519136)),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 12, 3, 51, 519136)),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.IntegerField(default=None)),
                ('floor_number', models.IntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
            ],
        ),
    ]
