# Generated by Django 5.0.1 on 2024-02-14 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_alter_movement_movement_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='pin_code',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_finished_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 13, 3, 43, 954772)),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_started_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 13, 3, 43, 954772)),
        ),
    ]
