name: Python template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Format code
      run: |
        make format
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        export DATABASE_URL=postgresql://dev_user:my_dev_password@db/my_dev_database

        make test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    
    
