name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create and activate virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Run docker compose file
        run: |
          docker compose up -d --build
      - name: Initialize dependencies
        run: |
          pip install -r requirements.txt
      - name: Test API endpoints
        run: |          
          pytest tests/test_weather.py
